### PR TITLE
Moved duplicated IPlaylistItem attributes to the root interface

### PR DESCRIPTION
**Pull request by Selbi182**
It always annoyed me that ever since Podcasts were added, I had to manually cast the IPlaylistItems to either Track or Episode. Even when all I needed was, for example, the ID, which is one of many attributes both Episode and Track share.

This change simply adds the shared attributes to the root interface. Some inconsistencies have been renamed as a result (such as Tracks calling it getIsExplicit while Episodes call it getExplicit).

### CODE REVIEW

**Comment by dargmuesli** [comment]
Thank you for your contribution! This was already discussed. See https://github.com/thelinmichael/spotify-web-api-java/issues/213 and https://github.com/thelinmichael/spotify-web-api-java/pull/214. Please direct your naming suggestions to Spotify too :)
Thanks again.

**Comment by Selbi182** [comment]
If the renaming of method is your concern then I'd be happy to put those back into their individual classes. Really, all I'm asking for is to have getId() in the interface, the rest is just a bonus.

**Comment by dargmuesli** [comment]
Go for it ;)

**Comment by Selbi182** [comment]
There, now it's just the methods that are exactly identical in both Episodes and Tracks. Of course, this is a design philosophy question, but I feel like Spotify slipped up here. There's no reason why they would call it stuff like audioPreviewUrl and also previewUrl, other than somebody doing an oopsie somewhere down the line.

Oh well, IT.

**Review by dargmuesli — APPROVED** [review]
LGTM

**Pull request merged**
