### PR TITLE
Small improvements, add self-type to request builders

### PR DESCRIPTION
**Pull request by WagnerChristoph**
- fix typos in documentation and `AuthorizationCodeRefreshRequest` class name
- correct and improve some documentation 
- add missing `final` modifier to two Builder subclasses
- unify BuilderType type parameter name and add type bounds in IPaging(Cursorbased)RequestBuilder
- introduce self() method to avoid casts in `AbstractRequest.Builder`

### CODE REVIEW

**Comment by WagnerChristoph** [comment]
Mostly by using the "spelling inspection" in IntelliJ. 😃

**Comment by dargmuesli** [comment]
I turned those off - too many false positive squiggly lines 😂

**Comment by Selbi182** [comment]
I have just upgraded to the new version and have run into some problems now. This might be some basic Java stuff but I don't know what to do here.

To deal with automatic retries on 429 errors I've written a utility method that looks like this:

```/**
 * Executes a single "greedy" Spotify Web API request, meaning that on potential
 * <i>429 Too many requests</i> errors the request will be retried ad-infinitum
 * until it succeeds. Any attempts will be delayed by the response body's given
 * <code>retryAfter</code> parameter, in seconds.
 * 
 * @param <T> the injected return type
 * @param <BT> the injected Builder
 * @param requestBuilder the basic, unbuilt request builder
 * @return the single result item
 */
public static <T, BT> T executeWithRetry(IRequest.Builder<T, BT> requestBuilder) throws SpotifyWebApiException, IOException {
	try {
		IRequest<T> builtRequest = requestBuilder.build();
		T result = builtRequest.execute();
		return result;
	} catch (TooManyRequestsException e) {
		int timeout = e.getRetryAfter() * 1000;
		Thread.sleep(timeout * RETRY_TIMEOUT_4XX);
		return execute(requestBuilder);
	}
}```

And to call it all I would do is this:

```Album execute = SpotifyApiUtils.executeWithRetry(spotifyApi.getAlbum(albumId));```

This had the added bonus of not having to write `.build()`, though that's just for convenience. It worked fine until the upgrade to Version 5 of the API.

I strongly believe this is because of the drastically changed BuildType parameters and I can't figure out the correct method signature anymore. I've tried this, but it still doesn't work:

```public static <T, BT> T executeWithRetry(IRequest.Builder<T, Builder<T, ?>> requestBuilder) {```

But that just changes the error message to

> The method execute(IRequest.Builder<T,IRequest.Builder<T,?>>) in the type SpotifyCall is not applicable for the arguments (GetAlbumRequest.Builder)

I'd rather not stay at Version 4 if I can help it. What am I doing wrong here?

**Comment by dargmuesli** [comment]
Does `public static <T, BT extends IRequest.Builder<T, ?>> T executeWithRetry(IRequest.Builder<T, BT> requestBuilder) throws SpotifyWebApiException, IOException, InterruptedException {` do the trick?

**Comment by dargmuesli** [comment]
In case you, @WagnerChristoph, have some free time sometime in the future it'd be very kind if you'd fix the "raw use of parameterized class" warning in this line: https://github.com/thelinmichael/spotify-web-api-java/blob/b438f971c3a6723379895044ef7bb35ba797169a/examples/data/personalization/GetUsersTopArtistsAndTracksExample.java#L23
Throw those generics around as you like, those are somewhat beyond me :D

**Comment by Selbi182** [comment]
> 
> 
> Does `public static <T, BT extends IRequest.Builder<T, ?>> T executeWithRetry(IRequest.Builder<T, BT> requestBuilder) throws SpotifyWebApiException, IOException, InterruptedException {` do the trick?

It does! Thank you so much!

**Pull request merged**
