### PR TITLE
Added Missing "album_group" attribute of AlbumSimplified

### PR DESCRIPTION
**Pull request by ZhectorSM**
Added album_group attribute
Fixed releaseDate and releaseDatePrecision attributes on JsonUtils builder
Related to #180

### CODE REVIEW

**Comment by dargmuesli** [comment]
Would you please create another PR for filling the new data into https://github.com/thelinmichael/spotify-web-api-java/blob/master/src/test/fixtures/requests/data/artists/GetArtistsAlbumsRequest.json?

**Comment by Selbi182** [comment]
Thank you so much for the fix! One tiny thing though...

grafik

Why didn't you reuse the AlbumType enum? Not that it's a big deal to just use AlbumType.valueOf(), but I'm not sure if this was intentional.

**Comment by ZhectorSM** [comment]
> Would you please create another PR for filling the new data into https://github.com/thelinmichael/spotify-web-api-java/blob/master/src/test/fixtures/requests/data/artists/GetArtistsAlbumsRequest.json?

Sure, I'll work on it

**Comment by ZhectorSM** [comment]
> Thank you so much for the fix! One tiny thing though...
> 
> grafik
> 
> Why didn't you reuse the AlbumType enum? Not that it's a big deal to just use AlbumType.valueOf(), but I'm not sure if this was intentional.
> 
> EDIT: keyOf, not valueOf.

Hi,
There is no special argument. I'm just starting to work on the project.
If could you explain to me the relation between the AlbumType enum and AlbumGroup? or how should work? I could fix it in a future commit

Thanks

**Comment by dargmuesli** [comment]
Well this is somewhat ambiguous. Actually it looks like we need a copy of AlbumType named AlbumGroup. And `APPEARS_ON` must then be removed from AlbumType.

**Comment by Selbi182** [comment]
> Hi,
> There is no special argument. I'm just starting to work on the project.
> If could you explain to me the relation between the AlbumType enum and AlbumGroup? or how should work? I could fix it in a future commit
> 
> Thanks

AlbumGroup is exactly like AlbumType, it's one of four types (album, single, compilation, appears_on). If I'm getting this right it should really only be relevant for "APPEARS_ON" releases if you fetch an artist's albums.

> Well this is somewhat ambiguous. Actually it looks like we need a copy of AlbumType named AlbumGroup. And `APPEARS_ON` must then be removed from AlbumType.

You think? I thought it was specifically added so you could properly group APPEARS_ON releases when queried using GetAnArtistsAlbums. At least that was my problem since AlbumType alone gets lost in there.

**Comment by dargmuesli** [comment]
> You think? I thought it was specifically added so you could properly group APPEARS_ON releases when queried using GetAnArtistsAlbums. At least that was my problem since AlbumType alone gets lost in there.

Sorry, I meant "was ambiguous".

**Comment by dargmuesli** [comment]
Done.
e8f96411d976fdab60f7050ea78f8e94bb743da4

**Pull request merged**
