### PR TITLE
Fixes assertion for SetVolumeForUsersPlaybackRequest.volume_percent

### PR DESCRIPTION
**Pull request by Bart1909**

### CODE REVIEW

**Comment by Dargmuesli** [comment]
Thanks! Could you please do a quick search through the code if this occurs somewhere else too?

**Comment by Bart1909** [comment]
Looks fine for all others <= and >= as well as for < and >

**Comment by Dargmuesli** [comment]
Oops, I've merged right when you added the second commit. That one is not indented correctly and thus one cannot easily see what was changed exactly. But no problem though, just create separate branches for each fix and send separate pull requests. I'll tell you when I've reset the merged changes.

**Comment by Dargmuesli** [comment]
Reverted and fixed in #133 & #134.

**Pull request merged**
