### PR TITLE
Added support for recommendations requests.

### PR DESCRIPTION
**Pull request by dhughes**
Hi this adds the required classes and methods to support the Spotify recommendations api documented here: https://developer.spotify.com/web-api/get-recommendations/

I think this follows all of your practices. Let me know if you need anything revised or changed.

### CODE REVIEW

**Comment by dhughes** [comment]
After submitted this PR I realized I'd forgotten to update some tests. These have been changed and should be a part of this PR now.

**Comment by dhughes** [comment]
Bump?

**Comment by Dargmuesli** [comment]
Thanks for the tests!

I've added the `invalid` tag because this feature was merged into branch `v2_requests`, but not into the `master` branch yet. This way I have a better overview over all PRs.

**Comment by dhughes** [comment]
Woah! It lives! 😉

**Comment by Dargmuesli** [comment]
;) see #72 for explanation. 
Merry Christmas!

**Pull request merged**
