### PR TITLE
WIP: Add more Javadoc

### PR DESCRIPTION
**Pull request by c-schuhmann**
I will add more and more commits to this pull request. I start with the model objects and after that I continue with the requests.

### CODE REVIEW

**Comment by Dargmuesli** [comment]
Have a look at [GetAlbumRequest.java in v2_requests](https://github.com/thelinmichael/spotify-web-api-java/blob/v2_requests/src/main/java/com/wrapper/spotify/requests/data/albums/GetAlbumRequest.java) and similar, where I've added information taken from [beta.developer.spotify.com](https://beta.developer.spotify.com/documentation/web-api/reference/albums/get-album/) before you start working on the requests. And if possible wait for me to finish working on the request classes before you start to add documentation :)

**Comment by Dargmuesli** [comment]
I've updated [GetAlbumRequest.java in v2_requests](https://github.com/thelinmichael/spotify-web-api-java/blob/v2_requests/src/main/java/com/wrapper/spotify/requests/data/albums/GetAlbumRequest.java). Please pay attention to
- links (both `@link` and `<a></a>`)
- full coverage
- closeness to [beta.developer.spotify.com](https://beta.developer.spotify.com/documentation/web-api/reference/albums/get-album/)
- 120 characters per line limit

**Comment by Dargmuesli** [comment]
If you come up with own ideas / standards for documentation please add them to #95 for discussion! :)

**Comment by c-schuhmann** [comment]
Okay, I will pay more attention to this standards when adding new Javadoc :) But I start with new files first, after that I check the other files I already commented. And I think it takes some time until I reach the request classes, so don't worry :)

**Comment by c-schuhmann** [comment]
And we should keep in mind that the URLs leading to [beta.developer.spotify.com](https://beta.developer.spotify.com/documentation/web-api/reference/albums/get-album/) might change in the future... But replacing them sometime shouldn't be a problem :)

**Comment by Dargmuesli** [comment]
You're right on this. I only meant closeness with the meaning of closeness to data on [beta.dev...](https://beta.developer.spotify.com/) and I think that won't change much. It's more like a new webdesign as far as I can tell from the parts I've read. Eventhough the content should change a little bit in my opinion as many lists are only partly alphabetically sorted which makes it irritating to compare to our java class files. But that's only my 2cents.

I've replaced links to [beta.dev...](https://beta.developer.spotify.com/) with their [developer.spotify.com](https://developer.spotify.com/) representation in commit c2e1eeb7a62794caad95f5259970c9fe936d7ae7. They should not be parts of the documentation, in contrast to the site's content as far as that's possible.

**Comment by Dargmuesli** [comment]
Let's simplify this a bit @c-schuhmann. I've almost lost overview with all those similar named branches. And given the speed the code is currently changing, I'd recommend we switch back to your original suggestion to submit individual PRs. Otherwise it becomes a pain to merge as I've seen today. I hope I've not accidentially forgotten any of your changed while solving conflicts. Thanks for your patience!

**Comment by c-schuhmann** [comment]
Okay, then let's go back to individual PRs. It's really easier to keep track of everything when I submit single PRs.

**Pull request merged**
