### PR TITLE
CodeCov for all the builds

### PR DESCRIPTION
**Pull request by mformihir**
Earlier, I added CodeCov code coverage using the Cobertura plugin which does not support the latest versions of Java.
Finally, I set up code coverage using JaCoCo plugin and it supports code coverage for all the versions of Java.

### CODE REVIEW

**Comment by dargmuesli** [comment]
Thanks a lot!

**Comment by dargmuesli** [comment]
Just a little hint: it's always a good idea to create a separate branch in your repo for PRs :)

**Comment by mformihir** [comment]
I'll keep that in mind! :)

**Comment by mformihir** [comment]
Just a casual question that keeps me bugging: When do the **develop** (and other) branches get merged into **master**, is there an interval when the **develop** branch gets reviewed or something else? 
Curious to know. :)

**Comment by dargmuesli** [comment]
Well, if there are changes to the source which require a new release for other projects, that depend in this, to include, then a new version is release = develop is merged into master. Or if someone would like me to. Do you want a new release? 😉

**Comment by mformihir** [comment]
Looking at the fixes from the older PRs and the recent addition of code coverage results on the "home" page of the repo (README.md), yes! I think now would be a nice time to merge the changes into **master**, although, you have a better idea at this than me.

But yes, I want a new release :)

**Comment by dargmuesli** [comment]
Actually, the development branch should be the default branch and thus displayed by default. I don't have the permissions to set this up though, maybe @thelinmichael finds a second to help us out.

**Comment by mformihir** [comment]
As you have recently merged into master, the code coverage results are visible by default, and changing the default branch will result in the same, so, great. 
But, there have to be some problems with the latest Travis build. It initially shows a **build fail**, I checked the build errors and a click to the 'current' tab on Travis CI unexpectedly shows a **successful build**.
If you know what's going on with it, or are familiar with such fails, I'd love to know why! :)

**Comment by dargmuesli** [comment]
[4.2.1](https://github.com/thelinmichael/spotify-web-api-java/releases/tag/4.2.1) is on its way :)

**Comment by dargmuesli** [comment]
Somehow 6f07c4fac6dc37ba194d4e70c44ef867806f9153 changed the `before-deploy.sh` script's permissions the other way around. I fixed this and force-pushed master (as no one else is working on it).

**Comment by mformihir** [comment]
Thanks! This is the first repo I have contributed to, and it feels great. The experience was awesome!
Really looking forward to a lot more contributions. :)

**Comment by dargmuesli** [comment]
Wow, you did a great job! Thank you for the feedback, that lightened up my day 😄

**Comment by mformihir** [comment]
Who knew the first maintainer I have a conversation with would be a DJ! 🔥

**Pull request merged**
